### ISSUE TITLE
Reconsile Documentation Conversion Issues

### ISSUE THREAD

**Issue by ronytomen** [Cacti/documentation#6]
Moving forward and not looking back, we got ourselves into a pickle!

We need to compare and repair the current `develop` branch documentation with the originally converted `manual.md`.

There are missing tables and other elements that need to be put into the newer split file documentation.

Original manual located at: https://github.com/Cacti/documentation/blob/0e19461f7d99fc4cbe907888ebdd9c082d491d31/manual.md

Rendered manuals:
https://www.cacti.net/downloads/docs

***File Status***
- [x] [Command-Line-Scripts.md](https://github.com/Cacti/documentation/blob/develop/Command-Line-Scripts.md)
- [x] [Data-Input-Methods.md](https://github.com/Cacti/documentation/blob/develop/Data-Input-Methods.md)
- [x] [Data-Queries.md](https://github.com/Cacti/documentation/blob/develop/Data-Queries.md)
- [x] [Debugging.md](https://github.com/Cacti/documentation/blob/develop/Debugging.md)
- [x] [Documentation-Standards.md](https://github.com/Cacti/documentation/blob/develop/Documentation-Standards.md)
- [x] [Frequently-Asked-Questions.md](https://github.com/Cacti/documentation/blob/develop/Frequently-Asked-Questions.md)
- [x] [General-Installing-Instructions.md](https://github.com/Cacti/documentation/blob/develop/General-Installing-Instructions.md)
- [x] [Graph-Overview.md](https://github.com/Cacti/documentation/blob/develop/Graph-Overview.md)
- [x] [Graph-a-Single-SNMP-OID.md](https://github.com/Cacti/documentation/blob/develop/Graph-a-Single-SNMP-OID.md)
- [x] [How-to-Graph-a-Custom-Collection-Script.md](https://github.com/Cacti/documentation/blob/develop/How-to-Graph-a-Custom-Collection-Script.md)
- [x] [How-to-Graph-Your-Network.md](https://github.com/Cacti/documentation/blob/develop/How-to-Graph-Your-Network.md)
- [x] [Installing-Under-Windows.md](https://github.com/Cacti/documentation/blob/develop/Installing-Under-Windows.md)
- [x] [PHP-Script-Server.md](https://github.com/Cacti/documentation/blob/develop/PHP-Script-Server.md)
- [x] [Plugin-Development.md](https://github.com/Cacti/documentation/blob/develop/Plugin-Development.md)
- [x] [Principles-of-Operation.md](https://github.com/Cacti/documentation/blob/develop/Principles-of-Operation.md)
- [x] [RRDtool-Specific-Features.md](https://github.com/Cacti/documentation/blob/develop/RRDtool-Specific-Features.md)
- [x] [Requirements.md](https://github.com/Cacti/documentation/blob/develop/Requirements.md)
- [x] [Spine.md](https://github.com/Cacti/documentation/blob/develop/Spine.md)
- [x] [Templates.md](https://github.com/Cacti/documentation/blob/develop/Templates.md)
- [x] [Upgrading-Cacti.md](https://github.com/Cacti/documentation/blob/develop/Upgrading-Cacti.md)
- [x] [User-Management.md](https://github.com/Cacti/documentation/blob/develop/User-Management.md)
- [x] [Variables.md](https://github.com/Cacti/documentation/blob/develop/Variables.md)
- [x] [Version-Specific-Release-Notes.md](https://github.com/Cacti/documentation/blob/develop/Version-Specific-Release-Notes.md)
- [x] [Viewing-Graphs.md](https://github.com/Cacti/documentation/blob/develop/Viewing-Graphs.md)

**Comment by jpobeda** [comment]
@ronytomen 

You are pointing that link as the original source of manual.md right? 
the one that suppose to have more data than develop branch.

I went through all of it and there are actually missing stuff on the original rather than the one in the develop branch.

For instance if you look at https://github.com/Cacti/documentation/blob/0e19461f7d99fc4cbe907888ebdd9c082d491d31/manual.md#host-variables

You'll see that the host variables table is missing on the original one. But it's on the develop one..

If I'm going to work under the assumption that develop should have everything from the original, make sure the original isn't corrupted otherwise it shouldn't be the source and we should be using something else.

As far as it goes..only thing is `Aggregate-Overview.md` doesn't exist anywhere but it's part of the new content menu 

https://github.com/Cacti/documentation/blob/develop/Aggregate-Overview.md

**Comment by jpobeda** [comment]
Or maybe, what you're looking for is to find these missing tables

Eg.:
https://www.cacti.net/downloads/docs/html/user_management.html#EDIT_EXISTING_USER
Table 9-1. Field Description: User Management

It's not on https://github.com/Cacti/documentation/blob/develop/User-Management.md#editing-an-existing-user

**Comment by netniV** [comment]
Hi Javier,

The original conversion from the docs website was into the manual.md that was then split into separate section files that we now have on the repo.  That split was based on a certain title level so may not 100% match the original source for layout.

Also, I think I added a section for Aggregates as the content was missing in the source but was part of the original plugin.  So, there could well be updated information already in the repo.  Unfortunately, that is a point where manual review is going to be needed.

I would agree with the second post, we need to identify missing tables, images and content.  That is a good example of one.  As a priority, this should be done first so that we no longer need to go back to the source material but instead just be updating the repo with better, more up to date, information.

**Comment by jpobeda** [comment]
Hi Mark, thanks for that. I think i now know the whole story and I understand what to do next.

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by TheWitness** [comment]
Guys, I spent all day poking at this bear.  This specific list is 'almost done'.

**Comment by TheWitness** [comment]
Closing this one.  Plugins will be handled in the latest ticket.  Making good progress.
